### PR TITLE
support encrypted EBS volumes

### PR DESCRIPTION
**Pull request by scalp42**
I remember seeing PRs related to the `right_aws` gem, so this is for `aws-sdk` one, now that we don't depend on the old one anymore.

Per:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html

and

http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#create_volume-instance_method

### CODE REVIEW

**Comment by otakup0pe** [comment]
LGTM :cocktail:

**Comment by mrsipan** [comment]
+1

**Comment by arnaud036** [comment]
+1

**Comment by callmeradical** [comment]
+1 This is a feature very much needed.

**Comment by scalp42** [comment]
@callmeradical I'll push the added param. Good catch!

**Comment by scalp42** [comment]
@callmeradical should have the extra KMS bits now!

**Comment by callmeradical** [comment]
+1 for great justice

**Comment by DrMerlin** [comment]
+1

**Comment by scalp42** [comment]
@cwebberOps @someara @jtimberman any chance to review this PR please?

Sorry for the ping but it's for a good cause (stop the forks).

**Comment by scalp42** [comment]
Rebased on 2.6.6

**Comment by callmeradical** [comment]
Thanks Obama, I mean @someara

**Comment by DrMerlin** [comment]
Stop the forks!

**Pull request merged**
