### PR TITLE
digs into pageable response for snapshot lists

### PR DESCRIPTION
**Pull request by drywheat**
change required by aws-sdk v2 gem

### CODE REVIEW

**Comment by drywheat** [comment]
Also added a check for the snapshot state because attempting to create an EBS volume from a snapshot in a "pending" state results in an error.

**Comment by scalp42** [comment]
LGTM

**Comment by drywheat** [comment]
How do we get this merged into master?

**Comment by scalp42** [comment]
Need to wait for a guy from Opscode to look at it @drywheat :crystal_ball:

**Comment by miketheman** [comment]
Thanks!

**Pull request merged**
