### PR TITLE
Convert to use aws-sdk instead of right_aws

### PR DESCRIPTION
**Pull request by ubiquitousthey**
This converts all providers to use aws-sdk.  This allows S3 to use the iam-profile and opens up other options as aws-sdk supports a much larger range of aws services.

### CODE REVIEW

**Comment by pburkholder** [comment]
@cwebberOps How about merging this in? aws-sdk is the right thing, and I can see the folks are already starting to fork @ubiquitousthey for this feature. I'd be happy to discuss testing.

**Comment by ubiquitousthey** [comment]
BTW, I have run all existing tests successfully with this branch.

**Comment by ubiquitousthey** [comment]
What do I need to do to get this merged in?

**Comment by heph** [comment]
https://aws.amazon.com/blogs/aws/now-available-version-2-of-the-aws-sdk-for-ruby/ <=- it's officially out of preview. We should update the version and merge.

**Comment by jmassara** [comment]
Any progress on getting this merged?

**Comment by dblessing** [comment]
:+1: The current `right_aws` gem is no longer maintained. Please merge support for `aws_sdk`

**Comment by dblessing** [comment]
@someara Thanks!

**Comment by bharat109puri** [comment]
Is there any update on its merge.
Still i am getting the same error while using updated version of "aws" cookbook.
But its working fine using aws sdk, 
example 

aws s3 --region us-east-1 cp s3://#{node['s3']['bucket_name']}#{node['s3']['path_of_file']} #{node['your_system_path']['filename']}

**Pull request merged**
