### PR TITLE
Don't request region unless we are on ec2

### PR DESCRIPTION
**Pull request by ubiquitousthey**
If we aren't on ec2 (and we are probably using s3) just default to us-east-1

### CODE REVIEW

**Comment by scalp42** [comment]
Looks good :+1:

**Comment by asivitz** [comment]
Could we specify the region as an attribute? Seems like a better longterm solution.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @asivitz

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by asivitz** [comment]
Oh jeez. I don't have a marketplace account. You can revert my commit, or make a similar commit on a different branch. Or call it an Obvious Fix or whatever.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by ubiquitousthey** [comment]
OK.  I have fixed this and it pulls from an attribute.  Please merge.

**Comment by miketheman** [comment]
@ubiquitousthey I think this looks legit.

One note I'd make is that there's a pattern in this library for creating methods that encapsulate the logic behind querying for a variable and responding with 'something' - see examples of `instance_availability_zone` - which uses this kind of pattern.

You might want to factor that out to a method, then squash commits to give this another go.

**Comment by mkantor** [comment]
@miketheman do you mean something like [this](https://gist.github.com/mkantor/0641c37fc29d364ed071#file-ec2-rb-L54-L84)?

Looking up the region is a bit different from the other `query_*`-based stuff because it's not a separate query (the region is parsed out of the availability zone).

**Comment by miketheman** [comment]
@mkantor I think I see your point - as well as adding the extra method may fail itself. 

I guess if this is squashed, we can proceed.

**Comment by scalp42** [comment]
@ubiquitousthey any chance you can make it happen please? :pray:

**Comment by ubiquitousthey** [comment]
OK.  See PR #160 for the squashed commits

**Comment by ubiquitousthey** [comment]
Closing this in favor of #160.

**Pull request closed without merging**
